# Use a lightweight Python image
FROM python:3.10.8-slim

# Set working directory
RUN mkdir /app
WORKDIR /app

# Copy necessary files
COPY requirements.txt .
COPY src/ ./src
COPY models/ ./models
COPY data/ ./data
COPY logs/ ./logs

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose FastAPI's port
EXPOSE 8000

# Run FastAPI app
CMD ["python", "src/app.py"]
