name: CI/CD Pipeline

on:                         # Define when the workflow should run
  push:                     # Run when changes are pushed to 'main' branch
    branches:
      - test      # to be changed to main
  pull_request:             # Run when a pull request is created targeting 'main'
    branches:
      - test      # to be changed to main

jobs:                       # Define jobs
  test:
    name: Run Tests
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3   # Pulls latest code fro Github

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.8"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      #- name: Run Linting
      #  run: |
      #    pip install flake8
      #    flake8 src/ --max-line-length=250

      - name: Run Tests
        run: |
          pytest tests/

  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/test' # to be changed to main

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push API Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops-churn-api:latest -f Dockerfile.api .
          docker push ${{ secrets.DOCKER_USERNAME }}/mlops-churn-api:latest
        
      - name: Build & Push Monitoring Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mlops-churn-monitor:latest -f Dockerfile.monitor .
          docker push ${{ secrets.DOCKER_USERNAME }}/mlops-churn-monitor:latest
