apiVersion: v1
kind: PersistentVolume
metadata:
  name: tfx-pv
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /home/ahmedmoussa/training-files/ml-pipeline/us_pl3
  
